id: P004414
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24467
  title: ལེགས་པར་གསུངས་པ་འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོ་གསལ་བྱེད།
  author: ''
  volumes:
    a523409075554b26973109522c5830ba:
      image_group_id: I1KG24485
      title: ''
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
