id: P004414
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24467
  title: ལེགས་པར་གསུངས་པ་འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོ་གསལ་བྱེད།
  author: ''
  volumes:
    a523409075554b26973109522c5830ba:
      image_group_id: I1KG24485
      title: ''
      volume_number: 1
      total_pages: 472
